version: '3'

services:

  keycash-challenge:
    container_name: keycash-challenge
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-keycash
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres-keycash:
    container_name: postgres-keycash
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-keycash-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

volumes:
  postgres-keycash-data:

networks:
  app-connect:
      driver: bridge